# array_width
# attr_fn_like_width
# binop_separator
# blank_lines_lower_bound
# blank_lines_upper_bound
brace_style = "PreferSameLine"
# chain_width
color = "Always"
# combine_control_expr
# comment_width
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
# disable_all_formatting
# doc_comment_code_block_width
edition = "2024"
# emit_mode
# empty_item_single_line
# enum_discrim_align_threshold
# error_on_line_overflow
# error_on_unformatted
# float_literal_trailing_zero
# fn_args_layout
# fn_call_width
fn_params_layout = "Compressed"
fn_single_line = true
# force_explicit_abi
# force_multiline_blocks
# format_code_in_doc_comments
# format_generated_files
# format_macro_bodies
format_macro_matchers = true
# format_strings
# generated_marker_line_search_limit
# group_imports
hard_tabs = true
hex_literal_case = "Upper"
# hide_parse_errors
# ignore
imports_granularity = "Crate"
imports_indent = "Visual"
# imports_layout
# indent_style
# inline_attribute_width
# make_backup
# match_arm_blocks
# match_arm_indent
# match_arm_leading_pipes
# match_block_trailing_comma
# max_width
# merge_derives
# merge_imports
newline_style = "Unix"
# normalize_comments
normalize_doc_attributes = true
overflow_delimited_expr = true
# print_misformatted_file_names
# remove_nested_parens
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
# required_version
# short_array_element_width_threshold
# show_parse_errors
# single_line_if_else_max_width
# single_line_let_else_max_width
# skip_children
# skip_macro_invocations
space_after_colon = true
space_before_colon = true
# spaces_around_ranges
# struct_field_align_threshold
# struct_lit_single_line
# struct_lit_width
# struct_variant_width
# style_edition
# tab_spaces
trailing_comma = "Never"
# trailing_semicolon
# type_punctuation_density
# unstable_features
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
# wrap_comments